PR 669
ChangeCapTestOrg1/ChangeCapOrgTestRepo2Public pull request #669
Opened 2024-10-16 08:55 UTC by mailtesting244

#### PR Details
#### Ticket Type	  
- [] Feature
- [] Bug
- [] Task
		  
#### Feature/Ticket Status
- [] Partial (Not Ready for QA)
- [] Complete (Ready for QA)

#### External Ticket Link (i.e. Jira) - Paste link on a new line below:
https://ews2.atlassian.net/browse/IOP-5

2024-10-16 12:42 UTC, mainusamocvety approved these changes
[1m]

2024-10-16 12:43 UTC, mainusamocvety requested changes
dsg

2024-10-16 17:05 UTC, MikeSpedicy approved these changes
[3m]

2024-10-16 17:05 UTC, mainusamocvety approved these changes
[1m]

2024-10-16 17:24 UTC, MikeSpedicy approved these changes
[1m]

2024-12-17 14:51 UTC, mainusamocvety approved these changes
[1m]

2025-05-19 14:25 UTC, closed without merging